---
version: "2.0"

services:
  app:
    image: ubuntu:latest
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update ; apt-get upgrade -y ; apt-get install -y  curl ; curl -s https://raw.githubusercontent.com/Dimokus88/3proxy/main/start.sh | bash'   
    
    expose:
      - port: 80
        as: 80
        to:
      - port: 8088
        as: 8088
        to:
     
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1Gi
         
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
